apiVersion: batch/v1
kind: CronJob
metadata:
  name: tweet-today-in-taiwan-history
spec:
  schedule: "0 11 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: twitter-token
              secret:
                secretName: today-in-taiwan-history-bot-twitter-token
          containers:
            - name: tweet-today-in-taiwan-history
              image: gugod/today-in-taiwan-history-bot:latest
              command:
                - perl
                - /app/bin/tweet.pl
                - '--data'
                - /app/data
                - '-c'
                - /app/secrets/twitter-token.yml
                - '--yes'
              volumeMounts:
                - name: twitter-token
                  mountPath: /app/secrets
                  readOnly: true
          restartPolicy: Never
